export const formInitial = {
  id: undefined,
  fecha: '',
  inicioVerificacion: '',
  terminoVerificacion: '',
  oc: '',
  proveedor: '',
  origen: '',
  factura: '',
  especie: '',
  variedades: '',
  frioDescarga: '',
  cajasRecibidas: '',
  lineaTransportista: '',
  numeroContenedor: '',
  placasCamion: '',
  placasCaja: '',
  chofer: '',
  tempSetPoint: '',
  observacionesSetPoint: '',
  tempPantalla: '',
  observacionesPantalla: '',
  termografo: '',
  tempOrigen: '',
  tempDestino: '',
  limpio: '',
  cajaCerrada: '',
  lona: '',
  fauna: '',
  carga: '',
  seguridadCarga: '',
  sellado: '',
  resultadosInv: '',
  tempAPuerta: '',
  tempAMedio: '',
  tempAFondo: '',
  tempMPuerta: '',
  tempMMedio: '',
  tempMFondo: '',
  tempBPuerta: '',
  tempBMedio: '',
  tempBFondo: '',
  tempMax: '',
  tempMin: '',
  tempIdeal: '',
  nombreInspector: '',
  nombreChofer: '',
  option: '',
  option2: '',
  optionLimpio: '',
  optionCaja: '',
  optionLona: '',
  optionLibre: '',
  optionCarga: '',
  optionSeguridad: '',
  optionSellado: '',
  optiontarimasDanadas: '',
  optioncajasIdentificadas: '',
  optiondanadasManiobra: '',
  imagecumpletermografo: [],
  imagecumpletermografo2: [],
  imageLimpio: [],
  imageCajaCerrada: [],
  imageLonaBuenEstado: [],
  imageLibreFauna: [],
  imageCargaBuenEstado: [],
  imageSeguridadCarga: [],
  imageSellado: [],
  imagestarimasDanadas: [],
  imagescajasIdentificadas: [],
  imagesdanadasManiobra: [],
  tarimasDanadas: "",
  cajasIdentificadas: "",
  danadasManiobra: "",
};


export interface FormData {
  [key: string]: string | number | string[] | undefined
  termografo?: string | number | string[] | undefined
  id?: number
  fecha?: string
  inicioVerificacion?: string
  terminoVerificacion?: string
  oc?: string
  proveedor?: string
  origen?: string
  factura?: string
  especie?: string
  variedades?: string
  frioDescarga?: string
  cajasRecibidas?: string
  lineaTransportista?: string
  numeroContenedor?: string
  placasCamion?: string
  placasCaja?: string
  chofer?: string
  tempSetPoint?: string
  observacionesSetPoint?: string
  tempPantalla?: string
  observacionesPantalla?: string
  option?: string
  option2?: string
  tempOrigen?: string
  tempDestino?: string
  optionLimpio?: string
  limpio?: string
  optionCaja?: string
  cajaCerrada?: string
  optionLona?: string
  lona?: string
  optionLibre?: string
  fauna?: string
  optionCarga?: string
  carga?: string
  optionSeguridad?: string
  seguridadCarga?: string
  optionSellado?: string
  sellado?: string
  tarimasDanadas?: string
  cajasIdentificadas?: string
  danadasManiobra?: string
  tempAPuerta?: string
  tempMPuerta?: string
  tempBPuerta?: string
  tempAMedio?: string
  tempMMedio?: string
  tempBMedio?: string
  tempAFondo?: string
  tempMFondo?: string
  tempBFondo?: string
  tempMin?: string
  tempMax?: string
  tempIdeal?: string
  resultadosInv?: string
  nombreInspector?: string
  nombreChofer?: string
  imageLimpio?: string[]
  imageLibreFauna?: string[]
  imageCajaCerrada?: string[]
  imageLonaBuenEstado?: string[]
  imageCargaBuenEstado?: string[]
  imageSeguridadCarga?: string[]
  imageSellado?: string[]
  imagescajasIdentificadas?: string[]
  imagestarimasDanadas?: string[]
  imagesdanadasManiobra?: string[]
  imagecumpletermografo?: string[]
  imagecumpletermografo2?: string[]
  optiontarimasDanadas?: string
  optioncajasIdentificadas?: string
  optiondanadasManiobra?: string
}
