
export const fruitOptions = [
  { value: '4.7', label: 'Aguacates (4.7°C)' },
  { value: 'Ambiente', label: 'Ajo (Ambiente)' },
  { value: '4.4', label: 'Alcachofa (4.4°C)' },
  { value: '3.1', label: 'Arandano azul (3.1°C)' },
  { value: '2.2', label: 'Brócoli (2.2°C)' },
  { value: '14.2', label: 'Camote (14.2°C)' },
  { value: '3.6', label: 'Calabaza (3.6°C)' },
  { value: '0.7', label: 'Cereza (0.7°C)' },
  { value: '3.1', label: 'Ciruela (3.1°C)' },
  { value: '9.4', label: 'Cebollas Nacional (9.4°C)' },
  { value: '9.4', label: 'Cebollas Americana (9.4°C)' },
  { value: 'Ambiente', label: 'Cebolla Seca (Ambiente)' },
  { value: '1.0', label: 'Col de Bruselas (1.0°C)' },
  { value: '1.7', label: 'Chabacano (1.7°C)' },
  { value: '1.7', label: 'Durazno (1.7°C)' },
  { value: '1.7', label: 'Elote Dulce (1.7°C)' },
  { value: '4.6', label: 'Esparrago (4.6°C)' },
  { value: '0.7', label: 'Frambuesa (0.7°C)' },
  { value: '0.7', label: 'Fresa (0.7°C)' },
  { value: '7.7', label: 'Guayaba (7.7°C)' },
  { value: '5.6', label: 'Granada (5.6°C)' },
  { value: '1.7', label: 'Kiwi (1.7°C)' },
  { value: '6.9', label: 'Limón (6.9°C)' },
  { value: '6.4', label: 'Mandarina USA (6.4°C)' },
  { value: '6.4', label: 'Mandarina Peruana (6.4°C)' },
  { value: '6.4', label: 'Mandarina Nacional (6.4°C)' },
  { value: '2.2', label: 'Mango (2.2°C)' },
  { value: '3.1', label: 'Manzana Roja (3.1°C)' },
  { value: '3.1', label: 'Manzana Golden (3.1°C)' },
  { value: '3.1', label: 'Manzana Gala (3.1°C)' },
  { value: '3.1', label: 'Manzana Granny (3.1°C)' },
  { value: '2.8', label: 'Melón (2.8°C)' },
  { value: '6.4', label: 'Naranja (6.4°C)' },
  { value: '1.7', label: 'Nectarina (1.7°C)' },
  { value: '9.4', label: 'Papaya (9.4°C)' },
  { value: '9.4', label: 'Papa (9.4°C)' },
  { value: '8.9', label: 'Pepino (8.9°C)' },
  { value: '1.1', label: 'Pera anjou (1.1°C)' },
  { value: '1.1', label: 'Pera Asiatica (1.1°C)' },
  { value: '1.1', label: 'Pera Bosc (1.1°C)' },
  { value: '1.1', label: 'Pera Bartlett (1.1°C)' },
  { value: '1.7', label: 'Persimo (1.7°C)' },
  { value: '7.2', label: 'Pimiento (7.2°C)' },
  { value: '23.3', label: 'Sandía (23.3°C)' },
  { value: '11.7', label: 'Toronja (11.7°C)' },
  { value: '1.2', label: 'Uva (1.2°C)' },
  { value: '3.1', label: 'Zanahoria (3.1°C)' },
  { value: '0.7', label: 'Zarzamora (0.7°C)' }
]
